In [1]:
import pandas as pd
import feather

In [12]:
pre_sale_val = pd.read_feather(f'../data/input/pre_sale_val.f')

In [13]:
pre_sale_val.head()

,HOBBIES_1_001_CA_1_validation,HOBBIES_1_002_CA_1_validation,HOBBIES_1_003_CA_1_validation,HOBBIES_1_004_CA_1_validation,HOBBIES_1_005_CA_1_validation,HOBBIES_1_006_CA_1_validation,HOBBIES_1_007_CA_1_validation,HOBBIES_1_008_CA_1_validation,HOBBIES_1_009_CA_1_validation,HOBBIES_1_010_CA_1_validation,...,FOODS_3_818_WI_3_validation,FOODS_3_819_WI_3_validation,FOODS_3_820_WI_3_validation,FOODS_3_821_WI_3_validation,FOODS_3_822_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_827_WI_3_validation
0,0,0,0,0,0,0,0,12,2,0,...,0,14,1,0,4,0,0,0,0,0
1,0,0,0,0,0,0,0,15,0,0,...,0,11,1,0,4,0,0,6,0,0
2,0,0,0,0,0,0,0,0,7,1,...,0,5,1,0,2,2,0,0,0,0
3,0,0,0,0,0,0,0,0,3,0,...,0,6,1,0,5,2,0,2,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,5,1,0,2,0,0,2,0,0

In [3]:
day_info = pd.read_feather(f'../data/input/day_info.f')

In [4]:
day_info.head()

,day__2,day__3,day__4,day__5,day__6,day__7,day__8,day__9,day__10,day__11,...,day__22,day__23,day__24,day__25,day__26,day__27,day__28,day__29,day__30,day__31
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
wday_info = pd.read_feather(f'../data/input/wday_info.f')

In [9]:
wday_info.head()

   wday__2  wday__3  wday__4  wday__5  wday__6  wday__7
0        0        0        0        0        0        0
1        1        0        0        0        0        0
2        0        1        0        0        0        0
3        0        0        1        0        0        0
4        0        0        0        1        0        0

In [5]:
former_agg_event = pd.read_feather(f'../data/input/former_agg_event.f')

In [6]:
former_agg_event.head()

,Chanukah_End,Christmas,Cinco_De_Mayo,ColumbusDay,Easter,Eid_al_Fitr,EidAlAdha,Father_day,Halloween,IndependenceDay,...,OrthodoxEaster,Pesach_End,PresidentsDay,Purim_End,StPatricksDay,SuperBowl,Thanksgiving,ValentinesDay,VeteransDay,nba_finals_flag
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
former_agg_event.columns

Index(['Chanukah_End', 'Christmas', 'Cinco_De_Mayo', 'ColumbusDay', 'Easter',
       'Eid_al_Fitr', 'EidAlAdha', 'Father_day', 'Halloween',
       'IndependenceDay', 'LaborDay', 'LentStart', 'LentWeek2',
       'MartinLutherKingDay', 'MemorialDay', 'Mother_day', 'NewYear',
       'OrthodoxChristmas', 'OrthodoxEaster', 'Pesach_End', 'PresidentsDay',
       'Purim_End', 'StPatricksDay', 'SuperBowl', 'Thanksgiving',
       'ValentinesDay', 'VeteransDay', 'nba_finals_flag'],
      dtype='object')